shader_type canvas_item;
render_mode blend_mix;

uniform vec4 outline_color : source_color = vec4(0.0, 0.0, 0.0, 0.0);
uniform float outline_width : hint_range(0.0, 10.0) = 0.0;

void fragment() {
	vec4 col = texture(TEXTURE, UV);
	if (outline_color.a > 0.0 && outline_width > 0.0 && col.a < 0.1) {
		vec2 size = TEXTURE_PIXEL_SIZE * outline_width;
		float max_a = 0.0;
		max_a = max(max_a, texture(TEXTURE, UV + vec2(0.0, -size.y)).a);
		max_a = max(max_a, texture(TEXTURE, UV + vec2(0.0, size.y)).a);
		max_a = max(max_a, texture(TEXTURE, UV + vec2(-size.x, 0.0)).a);
		max_a = max(max_a, texture(TEXTURE, UV + vec2(size.x, 0.0)).a);
		max_a = max(max_a, texture(TEXTURE, UV + vec2(-size.x, -size.y)).a);
		max_a = max(max_a, texture(TEXTURE, UV + vec2(size.x, -size.y)).a);
		max_a = max(max_a, texture(TEXTURE, UV + vec2(-size.x, size.y)).a);
		max_a = max(max_a, texture(TEXTURE, UV + vec2(size.x, size.y)).a);
		
		if (max_a > 0.1) {
			COLOR = vec4(outline_color.rgb, outline_color.a * max_a);
		} else {
			COLOR = col;
		}
	} else {
		COLOR = col;
	}
}
